### ISSUE TITLE
Add userop.js and bundler

### ISSUE THREAD

**Issue by rrrliu** [zkwebauthn/webauthn-halo2#1]
Setup [ERC-4337 bundling](https://www.alchemy.com/best/account-abstraction-erc-4337-bundlers) locally, create a userOp and test it end-to-end.

**Comment by AlbertSu123** [comment]
Do you have a preference as for which bundler implementation to use? I've used pimlico in the past, there's also the eth infinitism bundler

**Comment by rrrliu** [comment]
No strong preference -- I've also seen [stackup](https://github.com/stackup-wallet/stackup-bundler) being used.
