### ISSUE TITLE
Investigate yul -> solidity function

### ISSUE THREAD

**Issue by rrrliu** [zkwebauthn/webauthn-halo2#2]
P256Verifier.sol is not working properly (rejects valid proof), even though the EVM bytecode from the compiled Yul works.

**Comment by AlbertSu123** [comment]
Do you have the yul source files? It seems like the P256Verifier doesn't compile at all, is it complete?

**Comment by rrrliu** [comment]
What's the compilation issue? The yul file is here: https://github.com/zkwebauthn/webauthn-halo2/blob/main/proving-server/P256Verifier.yul

**Comment by rrrliu** [comment]
Fixed with deployed EVM verifier approach
