### ISSUE TITLE
P256Account

### ISSUE THREAD

**Issue by rrrliu** [zkwebauthn/webauthn-halo2#3]
Extend [SimpleAccount](https://github.com/eth-infinitism/account-abstraction/blob/develop/contracts/samples/SimpleAccount.sol) to add P256 signature verification

**Comment by AlbertSu123** [comment]
Should I just extend P256Account with SimpleAccount? This should be pretty simple right?

**Comment by rrrliu** [comment]
Closed with #7. Thanks @AlbertSu123 for the fix 🚢
